version: '3.7'
services:
    mysql:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: mysql
        restart: always
        ports: 
            - 23306:3306
        environment: 
            MYSQL_ROOT_PASSWORD: "grupo7"
            MYSQL_DATABASE: "marketplace"
            MYSQL_USER: "allforone"
            MYSQL_PASSWORD: "userpwd"
        volumes: 
            - ./schemas:/var/lib/mysql:rw
        networks: 
            mysql_network:
                aliases: 
                    - mysql_host
volumes: 
    schema: {}
networks: 
    mysql_network:
        name: mysql_net
        driver: bridge